# Generated by Django 5.0.6 on 2024-05-11 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_alter_fotografia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='data_fotografia',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('NEBULOSA', 'Nebulosa'), ('PLANETA', 'Planeta'), ('ESTRELA', 'Estrela'), ('GALÁXIA', 'Galáxia')], default='', max_length=100),
        ),
    ]
