# Generated by Django 5.0.6 on 2024-05-11 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('PLANETA', 'Planeta'), ('NEBULOSA', 'Nebulosa'), ('GALÁXIA', 'Galáxia'), ('ESTRELA', 'Estrela')], default='', max_length=100),
        ),
    ]
